<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Page;

class PagesTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::statement('SET FOREIGN_KEY_CHECKS=0;');

		Page::truncate();

		Page::create([
			'id'            => 1,
			'title'         => 'Aviso de Privacidad',
			'description'   => 'Aviso de privacidad sobre el tratamiento de datos personales.',
			'content'       => '
<p>Estimado Cliente/Usuario:</p>
<p>Conforme a lo previsto en la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares (la &ldquo;Ley&rdquo;), y en cumplimiento de la obligaci&oacute;n a cargo de Cin&eacute;polis&reg; (a trav&eacute;s de EXHIBIDORA MEXICANA CINEPOLIS, S.A. de C.V.) consistente en proteger los datos personales de sus clientes, afiliados y/o beneficiarios de cualquiera de los productos o servicios pertenecientes al concepto comercialmente conocido como Cin&eacute;polis&reg; (tanto en complejos cinematogr&aacute;ficos, negocios relacionados, v&iacute;a telef&oacute;nica y en l&iacute;nea), hacemos de tu conocimiento lo siguiente:</p>
<p><strong>1. Contenido de los Datos Personales</strong><br>De acuerdo con la Ley, se entiende como &ldquo;Datos Personales&rdquo; cualquier informaci&oacute;n concerniente a una persona f&iacute;sica identificada o identificable. Para efectos del presente Aviso de Privacidad, de manera enunciativa mas no limitativa, se entender&aacute;n como &ldquo;Datos Personales&rdquo;:</p>
<p><strong>1.1. Datos generales</strong><br>Nombre(s) y apellidos, fecha de nacimiento, edad, sexo, estado civil, n&uacute;mero de hijos, domicilio, tel&eacute;fono fijo (de casa u oficina), tel&eacute;fono celular, correo electr&oacute;nico, y los datos e informaci&oacute;n que conforme a la Ley sean concernientes a una persona f&iacute;sica identificada o identificable.</p>
<p><strong>1.2. Datos relacionados con solicitudes de empleo</strong><br>Cuando ingreses o proporciones Datos Personales en o para la bolsa de trabajo de Cin&eacute;polis&reg;, adem&aacute;s de los datos generales, se considerar&aacute;n Datos Personales la informaci&oacute;n sobre nivel educativo, experiencia laboral y cualquier informaci&oacute;n relacionada con el curr&iacute;culum vitae que nos env&iacute;es.</p>
<p>En virtud de lo anterior, Cin&eacute;polis&reg; hace de tu conocimiento que cualquier vacante de trabajo disponible ser&aacute; publicada a trav&eacute;s de la plataforma en l&iacute;nea, la cual se encuentra disponible en la siguiente liga https://www.cinepolisjobs.com/, a trav&eacute;s de la cual los interesados podr&aacute;n postularse a trav&eacute;s de un registro en l&iacute;nea, por lo que cualquier Dato Personal referente a solicitudes de empleo que usted entregue a Cin&eacute;polis&reg;, ser&aacute; tratado conforme al Aviso de Privacidad publicado en esta plataforma en l&iacute;nea propiedad de Cin&eacute;polis&reg;.</p>
<p><strong>1.3. Revistas, programas y transacciones en l&iacute;nea</strong><br>Cuando te suscribas para recibir alguno de los productos de Cin&eacute;polis&reg; (productos tales como revistas impresas o electr&oacute;nicas, boletines electr&oacute;nicos, promociones, concursos, trivias, juegos, programas de lealtad, as&iacute; como los dem&aacute;s productos o servicios para los cuales se requiera realizar una suscripci&oacute;n para poder obtenerlos); cuando realices transacciones para la compra de boletos, alimentos, productos y/o servicios en nuestros complejos y negocios, as&iacute; como en cualquiera de nuestras plataformas digitales (mediante equipos m&oacute;viles y/o cualquier otra plataforma, sitios y/o micrositios web que de tiempo en tiempo utilice Cin&eacute;polis&reg;); y cuando realices transacciones y/u operaciones relacionadas y/o al interior de la plataforma de CineCash&reg; y/o de cualquier otra que de tiempo en tiempo este vigente; adem&aacute;s de los datos generales, se considerar&aacute;n Datos Personales los relacionados con tarjetas bancarias, tales como nombre del &nbsp;tarjetahabiente, n&uacute;mero de tarjeta, fecha de vencimiento de la tarjeta, tipo de tarjeta y c&oacute;digo de seguridad, adem&aacute;s del domicilio de entrega del producto y cualquier otra informaci&oacute;n necesaria para la suscripci&oacute;n o transacci&oacute;n en l&iacute;nea.</p>
<p>Al momento de que nos proporciones tus datos bancarios en cualquiera de nuestros medios de venta o comercializaci&oacute;n de los productos y/o servicios de Cin&eacute;polis&reg;, se entender&aacute; que desde ese momento est&aacute;s otorgando tu consentimiento expreso para que Cin&eacute;polis&reg; pueda realizar el tratamiento de dichos datos personales conforme a las finalidades del tratamiento establecidas en el numeral 4 inciso B) del presente Aviso de Privacidad.</p>
<p><strong>1.4. Datos de menores de edad</strong><br>Las p&aacute;ginas de Cin&eacute;polis&reg;, los sitios y micrositios en ellas contenidos, los formatos de inscripci&oacute;n a cualquiera de nuestros programas o servicios, as&iacute; como la recopilaci&oacute;n de informaci&oacute;n que tenga como fin el llevar a cabo cualquiera de las finalidades establecidas en el presente Aviso de Privacidad no fueron dise&ntilde;adas para el uso de menores de edad. Siendo el caso de que si, por error, obtenemos Datos Personales de estos, eliminaremos esa informaci&oacute;n de nuestros sistemas.</p>
<p>En caso de que por alguna situaci&oacute;n y/o confusi&oacute;n en alguna actividad o evento espec&iacute;fico se llegaran a recopilar datos personales de menores de edad, Cin&eacute;polis&reg; dar&aacute; aviso, a trav&eacute;s del presente aviso, a los padres y/o tutores inform&aacute;ndoles de las finalidades espec&iacute;ficas del tratamiento al que ser&aacute;n sometidos, as&iacute; mismo, se dar&aacute; cumplimiento a lo establecido en el siguiente p&aacute;rrafo.</p>
<p>Cin&eacute;polis&reg; podr&aacute; realizar el tratamiento de Datos Personales cuyos titulares sean menores de edad, velando por el uso adecuado de estos, y s&oacute;lo realizar&aacute; el tratamiento respetando el inter&eacute;s superior del menor y asegurando el respeto de sus derechos fundamentales, debiendo obtener la autorizaci&oacute;n expresa del representante legal del menor; as&iacute; mismo, en los casos en los que los menores de edad proporcionen sus datos personales al adquirir, inscribirse o suscribirse en alguno de nuestros productos o servicios de Cin&eacute;polis&reg;, mediante los cuales, no pueda corroborar de manera directa o indirecta la edad del menor o la autorizaci&oacute;n de sus padres o tutores, se entender&aacute; que los menores nos proporcionan sus datos personales previa consulta, asesor&iacute;a y autorizaci&oacute;n expresa de sus padres o tutores legales, conforme a lo establecido en el C&oacute;digo Civil Federal y en la legislaci&oacute;n aplicable.</p>
<p>Por lo anterior, en caso de que seas menor de edad, te solicitamos que previo a entregar a Cin&eacute;polis&reg; tus Datos Personales para participar y/o adquirir alguno de nuestros productos o servicios, lo consultes con tus padres y/o tutores y hasta no tener la autorizaci&oacute;n y asesor&iacute;a de estos, no nos los entregues.</p>
<p>Cin&eacute;polis&reg; se reserva el derecho de solicitar en cualquier momento la informaci&oacute;n y/o documentaci&oacute;n necesaria que permita acreditar la mayor&iacute;a de edad y/o la autorizaci&oacute;n expresa y por escrito de los menores de edad que nos hayan proporcionado los Datos Personales, por lo que en caso de no corroborar y/u obtener la informaci&oacute;n antes descrita, Cin&eacute;polis&reg; podr&aacute; eliminar sin perjuicio alguno la informaci&oacute;n y datos de nuestras bases de datos e, incluso, suspender y/o cancelar la venta y/o prestaci&oacute;n del servicio, conforme a los t&eacute;rminos y condiciones del producto o servicio que se trate.</p>
<p>Los padres y/o tutores de menores de edad en cualquier momento tendr&aacute;n el derecho de limitar, negar y solicitar la eliminaci&oacute;n de cualquiera que haya proporcionado el menor sin solicitar su autorizaci&oacute;n.</p>
<p><strong>1.5. Cookies</strong><br>Las cookies son archivos de texto que son descargados autom&aacute;ticamente y almacenados en un disco duro del equipo de c&oacute;mputo del usuario al navegar en una determinada p&aacute;gina de internet y que permiten al servidor de internet recordar algunos datos del usuario. Por medio de este Aviso de Privacidad te informamos que Cin&eacute;polis&reg; utiliza ciertas cookies para obtener informaci&oacute;n de la ciudad que seleccionas al consultar la cartelera o alguna otra informaci&oacute;n de Cin&eacute;polis&reg;, de manera que la siguiente ocasi&oacute;n en que ingreses al sitio de consulta, ya estar&aacute; precargada la ciudad elegida, as&iacute; mismo, y dependiendo de la transacci&oacute;n, producto y/o servicio de que se trate, Cin&eacute;polis&reg; puede utilizar dichas cookies con el objetivo de identificar o prevenir operaciones de comercio electr&oacute;nico que pudieran ser fraudulentas o de procedencia irregular o il&iacute;cita.</p>
<p><strong>1.6. Redes sociales</strong><br>Las redes sociales (tales como Facebook&reg;, Twitter&reg;, YouTube&reg;, LinkedIn&reg;, Instagram&reg; y/o las dem&aacute;s que de tiempo en tiempo est&eacute;n disponibles en el mercado) constituyen una plataforma de comunicaci&oacute;n y de interconexi&oacute;n entre plataformas digitales de los distintos usuarios, son ajenas a Cin&eacute;polis&reg; y, por lo tanto, no se encuentran bajo su responsabilidad. La informaci&oacute;n que proporciones dentro de redes sociales en las que Cin&eacute;polis&reg; participa como usuario, no constituye ni forma parte de los Datos Personales sujetos a la protecci&oacute;n de este Aviso de Privacidad, siendo responsabilidad de la empresa prestadora de esa plataforma y de quien lo publica.</p>
<p>En caso de que Cin&eacute;polis&reg; llegare a requerirte alg&uacute;n dato personal de los referidos en los puntos 1.1 al 1.4 o se llegaren a recopilar datos conforme a lo se&ntilde;alado en el 1.5 del Presente Aviso de Privacidad por medio y/o a trav&eacute;s de alguna red social, tales datos ser&aacute;n tratados conforme a las Finalidades del Tratamiento descritas a continuaci&oacute;n, ello seg&uacute;n correspondan al tipo de datos de que se trate. En este supuesto, los datos personales recaer&aacute;n bajo la responsabilidad de Cin&eacute;polis&reg;.</p>
<p>Sin embargo, por ser recolectados a trav&eacute;s de las redes sociales, &eacute;stas &uacute;ltimas tambi&eacute;n podr&aacute;n tener acceso o propiedad sobre tal informaci&oacute;n, ello dependiendo de las pol&iacute;ticas de uso, confidencialidad y tratamiento de la informaci&oacute;n de cada una de las redes sociales.</p>
<p>Los Datos Personales mencionados en los apartados 1.1. al 1.4. del presente Aviso de Privacidad ser&aacute;n recabados mediante el llenado de los formatos y/o mediante la recopilaci&oacute;n de informaci&oacute;n o documentaci&oacute;n requerida por Cin&eacute;polis&reg;, ya sea de manera personal o v&iacute;a electr&oacute;nica en cualquiera de las p&aacute;ginas de internet de Cin&eacute;polis&reg;, presentes o futuras (&ldquo;P&aacute;ginas de internet de Cin&eacute;polis&reg;&rdquo;), entre las que se destacan: https://cinepolis.com/, https://cinepolis.com/clubcinepolis-id/, https://www.cinepolisklic.com/ y/o https://www.cinepolisjobs.com/, as&iacute; como en los sitios o plataformas de Cin&eacute;polis&reg; ubicadas en las redes sociales en las cuales &eacute;ste &uacute;ltimo tiene o llegare a tener registro.</p>
<p>Nota: La titularidad de los derechos sobre las p&aacute;ginas de internet puede corresponder a EXHIBIDORA MEXICANA CINEPOLIS, S.A. de C.V., (&ldquo;EXHIBIDORA MEXICANA CIN&Eacute;POLIS&rdquo;) o bien, a cualquier otra sociedad integrante del grupo de empresas conocido como &ldquo;Cin&eacute;polis&reg;&rdquo;.</p>
<p><strong>1.7. Servicios de Call Center o ventas telef&oacute;nicas</strong><br>En los casos en los que adquieras alg&uacute;n producto o servicio de Cin&eacute;polis&reg; a trav&eacute;s de los servicios de operaci&oacute;n telef&oacute;nica que para tal efecto Cin&eacute;polis&reg; ponga a tu disposici&oacute;n, te informamos que para poder prestarte los servicios o proporcionarte los productos Cin&eacute;polis&reg; te podr&aacute; llegar a requerir v&iacute;a telef&oacute;nica alg&uacute;n dato personal de los referidos en los puntos 1.1 al 1.4 de la presente Pol&iacute;tica, tales datos ser&aacute;n tratados conforme a las Finalidades del Tratamiento descritas a continuaci&oacute;n, ello seg&uacute;n correspondan al tipo de datos de que se trate. En estos casos, te informamos que para tu seguridad y para el cumplimiento de la Legislaci&oacute;n aplicable, Cin&eacute;polis&reg; podr&aacute; llegar a grabar las llamadas o conversaciones a trav&eacute;s de los medios que juzgue pertinentes.</p>
<p>Asimismo, al momento de que nos proporciones tus Datos Personales v&iacute;a telef&oacute;nica se entender&aacute; que est&aacute;s otorgando tu consentimiento expreso para que Cin&eacute;polis&reg; pueda realizar el tratamiento de tus datos personales conforme a las establecidas en el presente Aviso de Privacidad, ello ya que tales Datos Personales son indispensables para la prestaci&oacute;n del servicio y/o para realizar la transacci&oacute;n que se trate.</p>
<p><strong>1.8. Videovigilancia</strong><br>Por razones de seguridad de nuestros clientes, Cin&eacute;polis&reg; podr&aacute; llegar a instalar equipos de videovigilancia en todos y/o en algunos de sus establecimientos, por lo que podr&aacute; llegar a recopilar im&aacute;genes, fotograf&iacute;as, videos, voces y/o sonidos que identifiquen o hagan identificables a nuestros clientes y/o a cualquier individuo que se encuentre o transite en y/o por las instalaciones de Cin&eacute;polis&reg;, ello dependiendo del rango de operaci&oacute;n y alcance del equipo de videovigilancia. La informaci&oacute;n videogr&aacute;fica recabada por estos equipos ser&aacute; autorizada preferentemente a petici&oacute;n de autoridades de investigaci&oacute;n y/o judiciales.</p>
<p><strong>2. Persona responsable de recabar Datos Personales</strong><br>La persona moral responsable de recabar tus Datos Personales (en este acto, as&iacute; como en actos pasados y/o futuros), es la persona moral denominada EXHIBIDORA MEXICANA CINEPOLIS, S.A. de C.V., (&ldquo;EXHIBIDORA MEXICANA CIN&Eacute;POLIS&rdquo;), la cual es integrante del grupo de empresas conocido como &ldquo;Cin&eacute;polis&reg;&rdquo;. Cualquier cambio respecto del responsable, ser&aacute; notificado conforme a las disposiciones legales vigentes.</p>
<p>Para efectos de lo establecido en la fracci&oacute;n I del art&iacute;culo 16 de la Ley, se se&ntilde;ala como domicilio de EXHIBIDORA MEXICANA CINEPOLIS, el ubicado en la Av. Cumbre de Naciones No. 1200, Zona Corporativos, Fraccionamiento Tres Mar&iacute;as, C.P. 58254, Morelia, Michoac&aacute;n.</p>
<p><strong>3. Tratamiento de tus Datos Personales</strong><br>De acuerdo con lo establecido en la Ley, se considera tratamiento de Datos Personales (&ldquo;Tratamiento de Datos Personales &ldquo;), la obtenci&oacute;n, uso, divulgaci&oacute;n o almacenamiento de Datos Personales, por cualquier &nbsp;medio. El uso abarca cualquier acci&oacute;n de acceso, manejo, aprovechamiento, transferencia o disposici&oacute;n de Datos Personales.</p>
<p>El Tratamiento de Datos Personales por parte de Cin&eacute;polis&reg; se limitar&aacute; al cumplimiento de las Finalidades previstas en el presente Aviso de Privacidad y se sujetar&aacute; a lo siguiente:</p>
<p>a) En caso de que se pretenda tratar tus Datos Personales para un fin distinto a los fines del presente Aviso de Privacidad, Cin&eacute;polis&reg; requerir&aacute; tu consentimiento para tal fin, de nueva cuenta.<br>b) Ser&aacute; el que resulte necesario, adecuado y relevante para los fines descritos en este Aviso de Privacidad.</p>
<p><strong>4. Finalidades del tratamiento de Datos Personales</strong><br>A trav&eacute;s del presente Aviso de Privacidad, Cin&eacute;polis&reg;, de conformidad a la II fracci&oacute;n del art&iacute;culo 16 de la Ley, declara que las finalidades del tratamiento de tus Datos Personales ser&aacute;n las siguientes (&ldquo;Finalidades del Tratamiento&rdquo;):</p>
<p>a) Fines comerciales, con el objeto de proveer nuestros productos o servicios, darte a conocer la informaci&oacute;n comercial de Cin&eacute;polis&reg;, entre la que se destaca de manera enunciativa y no limitativa, la relacionada con trivias, promociones, descuentos, beneficios, concursos, informaci&oacute;n de nuevos productos, felicitaciones de cumplea&ntilde;os, revista electr&oacute;nica, cambios en nuestros productos, etc.</p>
<p>b) Tratamiento para fines mercadol&oacute;gicos, publicitarios o de prospecci&oacute;n comercial.&nbsp;Con el objetivo de proporcionarte informaci&oacute;n, noticias de esta &iacute;ndole, que podr&iacute;a ser de tu inter&eacute;s, entre la que se destaca de manera enunciativa y no limitativa, la relacionada con publicidad sobre las pel&iacute;culas pr&oacute;ximas a estrenarse, informaci&oacute;n general del cine, pel&iacute;culas, productos y servicios de Cin&eacute;polis, as&iacute; como tambi&eacute;n solicitar evaluaci&oacute;n de la calidad en el servicio, realizar estudios internos sobre h&aacute;bitos de consumo y cualquier otro promocional o cuesti&oacute;n relacionada con los productos y/o servicios que forman parte del concepto comercialmente conocido como Cin&eacute;polis&reg;.</p>
<p>c) Cobro directo, telef&oacute;nico o en l&iacute;nea de revistas y transacciones, con el fin de realizar cargos a tarjetas bancarias de los productos adquiridos por los clientes de Cin&eacute;polis&reg;, ello derivado de las suscripciones y/o la compra de los productos o servicios de Cin&eacute;polis&reg;.</p>
<p>Los Datos Personales relacionados con informaci&oacute;n bancaria, &uacute;nicamente estar&aacute;n sujetos a las Finalidades del Tratamiento establecidas en el presente Aviso de Privacidad, por el tiempo que dure la transacci&oacute;n comercial y/o durante el tiempo en el que conforme a las operaciones de Cin&eacute;polis&reg; o la normatividad en la materia as&iacute; lo establezcan, ello con las finalidades de poder responder o aclarar futuras reclamaciones, aclaraciones o confirmaciones en relaci&oacute;n con las revistas y transacciones comerciales realizadas con Cin&eacute;polis&reg;, para poder proporcionar servicios de seguridad y prevenci&oacute;n de fraudes conforme a las plataformas y sistemas de seguridad con las que cuenta Cin&eacute;polis&reg; para estos efectos, para poder almacenar y utilizar dichos datos de manera posterior en transacciones u operaciones diferentes a la primera que los origin&oacute;, en cuyo caso, tales cargos o transacciones siempre se realizar&aacute;n, previo consentimiento previo y expreso de tu parte para el uso de tales datos, ello conforme a los mecanismos que para tal efecto determine Cin&eacute;polis&reg;.</p>
<p>d) Entrega de productos y cumplimiento de obligaciones con nuestros clientes, en caso de que adquieras alguna suscripci&oacute;n o realices una transacci&oacute;n electr&oacute;nica (boletos, alimentos, etc.), te hagas acreedor a alg&uacute;n premio derivado de las promociones, trivias o sorteos de Cin&eacute;polis&reg;, o para cumplir &nbsp;con las obligaciones que en su caso tengamos o llegaremos a tener contigo, utilizaremos tus Datos Personales para contactarte o enviarte los productos.</p>
<p>Por tal virtud, en caso de que te hagas acreedor a un premio derivado de las promociones, trivias o sorteos, Cin&eacute;polis&reg; podr&aacute; publicar tu nombre en alguna de sus p&aacute;ginas web y/o a trav&eacute;s de redes sociales.</p>
<p>e) Estudio, alta, selecci&oacute;n y/o contrataci&oacute;n de proveedores. Como requisito previo e indispensable para:</p>
<p>- Llevar a cabo los fines de la licitaci&oacute;n;<br>- Darte de alta como proveedor y mantener actualizada tu informaci&oacute;n en nuestro Cat&aacute;logo de Proveedores;<br>- Formalizar los acuerdos y/o documentaci&oacute;n requerida para asegurar un adecuado proceso de facturaci&oacute;n; y<br>- Cualquier otra medida necesaria para cuidar tus intereses.</p>
<p>f) Reclutamiento y selecci&oacute;n de personal, con el objetivo de que la persona inscrita en el portal en l&iacute;nea de Cin&eacute;polis Jobs y/o en cualesquiera de los programas de atracci&oacute;n, reclutamiento y selecci&oacute;n de personal reciba la informaci&oacute;n oportuna sobre ofertas de empleo o vacantes que surjan en Cin&eacute;polis&reg; y sus empresas afiliadas. As&iacute; mismo, con el objetivo de que Cin&eacute;polis&reg; pueda llevar a cabo los procesos de contacto, entrevistas y cualquier otro relacionado con sus procesos de reclutamiento y selecci&oacute;n de personal, ello ya sea que lo realice en su nombre y/o por medio de cualquier otra de sus empresas filiales o subsidiarias y/o alg&uacute;n tercero ajeno a Cin&eacute;polis&reg;, que pudiera facilitar alg&uacute;n servicio necesario para cualquier actividad relacionada con el proceso de selecci&oacute;n de candidatos para alguna vacante, por lo que Cin&eacute;polis&reg; siempre se asegurar&aacute; de que se cumplan con el tratamiento de datos se&ntilde;alado en el presente aviso de privacidad.</p>
<p>g) Requerimientos y cumplimiento de obligaciones de entidades p&uacute;blicas y administrativas, con el objetivo de dar respuesta a requerimientos de informaci&oacute;n de entidades p&uacute;blicas y administrativas en ejercicio de sus funciones legales o por orden judicial, as&iacute; como para la recopilaci&oacute;n de informaci&oacute;n, almacenamiento, entrega de avisos y cumplimiento de obligaciones a cargo de Cin&eacute;polis&reg; en relaci&oacute;n al cumplimiento de la Ley Federal para la Prevenci&oacute;n e Identificaci&oacute;n de Operaciones con Recursos de Procedencia Il&iacute;cita y dem&aacute;s normatividad aplicable.</p>
<p>h) Registro y conservaci&oacute;n de bases de datos para que Cin&eacute;polis&reg; pueda realizar todas y cada una de las actividades que le permitan realizar el almacenamiento y conservaci&oacute;n de la informaci&oacute;n en las bases de datos de Cin&eacute;polis&reg; y/o de cualquiera de sus empresas filiales, subsidiarias (nacionales o extranjeras) y/o pertenecientes al grupo Cin&eacute;polis&reg; que contengan datos personales.</p>
<p>j) Videovigilancia, en los casos en los que Cin&eacute;polis&reg; llegue a instalar c&aacute;maras y/o equipos de videovigilancia en todos o algunos de sus establecimientos, las im&aacute;genes, fotograf&iacute;as, videos, voces y/o sonidos captados por dichos equipos ser&aacute;n utilizados para la seguridad de la zona(s) videovigilada(s), para seguridad de nuestros clientes, empleados y/o de cualquier otra persona que transite en y/o por las instalaciones de Cin&eacute;polis&reg;.</p>
<p>Los datos e informaci&oacute;n personal mencionados en este punto y en el apartado 1.8 del presente Aviso de Privacidad, ser&aacute;n conservados durante el tiempo y plazos en los que Cin&eacute;polis&reg; determine convenientes para garantizar la seguridad del establecimiento que se trate y de las personas referidas en el p&aacute;rrafo anterior, as&iacute; como durante y por los plazos en los que la legislaci&oacute;n aplicable as&iacute; lo &nbsp;establezca, asimismo, dichos equipos podr&aacute;n llegar a proyectar im&aacute;genes pero no necesariamente grabarlas.</p>
<p>k) Finalidades que den origen o sean necesarias para la existencia, mantenimiento o cumplimiento de una relaci&oacute;n u obligaci&oacute;n jur&iacute;dica, estas finalidades son las que deriven de la celebraci&oacute;n de un contrato, acuerdo o v&iacute;nculo jur&iacute;dico del que derive una relaci&oacute;n jur&iacute;dica entre t&uacute; y Cin&eacute;polis&reg;, en las que Cin&eacute;polis&reg; tenga una obligaci&oacute;n jur&iacute;dica unilateral en tu beneficio y/o las que Cin&eacute;polis&reg; tenga a su cargo o a favor el cumplimiento de obligaciones, responsabilidades y/o ejercicio de derechos contractuales, legales y/o derivada de requerimientos de autoridades.</p>
<p>Para poder llevar a cabo lo anterior, ser&aacute; necesario que Cin&eacute;polis&reg; utilice tus Datos Personales, durante el tiempo en el que subsista la relaci&oacute;n u obligaci&oacute;n jur&iacute;dica entre t&uacute; y Cin&eacute;polis&reg;, y/o mientras subsistan obligaciones, derechos o responsabilidades ante Autoridades y/o derivadas de la legislaci&oacute;n aplicable.</p>
<p><strong>5. Aceptaci&oacute;n del tratamiento de Datos Personales</strong><br>Para que Cin&eacute;polis&reg; pueda llevar a cabo el Tratamiento de Datos Personales, nuestros clientes y/o titulares de Datos Personales deber&aacute;n otorgarnos la aceptaci&oacute;n expresa o t&aacute;cita para dicho tratamiento, la cual se llevar&aacute; por cualquiera de los siguientes medios:</p>
<p><strong>5.1 Aceptaci&oacute;n expresa</strong><br>Conforme a lo establecido en el art&iacute;culo 8 de la Ley, se entender&aacute; que expresaste tu consentimiento expreso para que Cin&eacute;polis&reg; realice el tratamiento de tus datos personales cuando manifiestes tu voluntad de manera verbal, por escrito, por medios electr&oacute;nicos, &oacute;pticos o por cualquier otra tecnolog&iacute;a, o por signos inequ&iacute;vocos.</p>
<p><strong>5.1.1. Aceptaci&oacute;n expresa a trav&eacute;s de medios electr&oacute;nicos</strong><br>Aceptaci&oacute;n o rechazo del Aviso de Privacidad por medios electr&oacute;nicos Publicaci&oacute;n en las p&aacute;ginas de internet de Cin&eacute;polis&reg;, adem&aacute;s de darte a conocer el Aviso de Privacidad mediante correo electr&oacute;nico, Cin&eacute;polis&reg; publicar&aacute; en su portal el presente Aviso de Privacidad, con el fin de que est&eacute; a tu disposici&oacute;n al momento en que as&iacute; lo requieras. La aceptaci&oacute;n o el rechazo del Aviso de Privacidad de Cin&eacute;polis&reg; por medios electr&oacute;nicos ser&aacute; efectuada de la siguiente manera:</p>
<p>a) Cin&eacute;polis&reg; pondr&aacute; a tu disposici&oacute;n el aviso de privacidad al momento de realizar el registro y/o cualquier operaci&oacute;n de servicios que Cin&eacute;polis&reg; proporcione en su sitio web, aplicaci&oacute;n m&oacute;vil o portal, por lo que al momento de que ingreses tus datos de forma voluntaria, que se solicitan para completar el formulario de registro u operaci&oacute;n, en el mismo acto Cin&eacute;polis&reg; dar&aacute; a conocer el presente Aviso de Privacidad, poniendo a tu disposici&oacute;n un recuadro con la leyenda de &ldquo;HE LE&Iacute;DO Y ACEPTO EL AVISO DE PRIVACIDAD&rdquo;, por lo que al momento de seleccionar el recuadro y concretar la operaci&oacute;n o registro y/o de dar clic, se entender&aacute; que has le&iacute;do y aceptado de forma expresa el tratamiento que Cin&eacute;polis&reg; dar&aacute; a tus datos personales.</p>
<p>b) Cin&eacute;polis&reg; podr&aacute; enviarte, a la direcci&oacute;n de correo electr&oacute;nico que tenga registrada a tu nombre, la siguiente informaci&oacute;n:<br>- La manifestaci&oacute;n de que existe un Aviso de Privacidad de Cin&eacute;polis&reg;, o las modificaciones o cambios que se realicen a dicho Aviso, en su caso.<br>- El contenido del Aviso de Privacidad y, en su caso, las actualizaciones o adecuaciones que se realicen al mismo.<br>- Un v&iacute;nculo electr&oacute;nico y/o correo electr&oacute;nico mediante el cual puedas aceptar o no los cambios que &eacute;ste llegare a tener.</p>
<p>c) Una vez que hayas le&iacute;do y est&eacute;s enterado del contenido del Aviso de Privacidad, o bien, de los cambios que se le realicen, tendr&aacute;s las siguientes opciones:</p>
<p>- Aceptar. Mediante tu aceptaci&oacute;n otorgas consentimiento expreso y autorizaci&oacute;n para que Cin&eacute;polis&reg; pueda utilizar tus Datos Personales de acuerdo a las Finalidades del Tratamiento establecidas en el Aviso de Privacidad.<br>- No aceptar. Cuando no aceptes el contenido del Aviso de Privacidad o sus modificaciones, niegas o cancelas tu consentimiento y autorizaci&oacute;n para que Cin&eacute;polis&reg; utilice tus Datos Personales. En este caso, Cin&eacute;polis&reg; cancelar&aacute; y dejar&aacute; de usar tus Datos Personales para las Finalidades del Tratamiento establecidas en el Aviso de Privacidad.</p>
<p>Lo anterior, con la salvedad de que si el tratamiento de los Datos Personales es necesario o indispensable para el cumplimiento de una obligaci&oacute;n y/o ejercicio de alg&uacute;n derecho surgido entre el titular de los Datos Personales y Cin&eacute;polis&reg;, as&iacute; como para el cumplimiento de obligaciones ante Autoridades, por lo que al momento de suscribir, adquirir o convenir respecto de los mismos, el Titular de los Datos Personales autoriz&oacute; el que los mismos fueran utilizados para el cumplimiento y/o ejercicio de tales derechos y obligaciones, por lo que el no aceptar el tratamiento de los mismos<br>de ninguna manera podr&aacute; cancelar los derechos previamente suscritos por el titular.</p>
<p>Por ello, en caso de que no llegares a aceptar el tratamiento de los datos de manera posterior al haber adquirido alg&uacute;n producto o servicio, suscrito alguna obligaci&oacute;n y/o al hacerte acreedor de alg&uacute;n derecho, tal negativa al tratamiento de tus datos personales tendr&aacute; efectos &uacute;nicamente respecto de las dem&aacute;s Finalidades del tratamiento establecidas en la presente Pol&iacute;tica que no formen parte del derecho u obligaci&oacute;n adquirida entre t&uacute; y Cin&eacute;polis&reg; y/o cuando sea suscrito de manera unilateral por alguno de ellos.</p>
<p><strong>5.1.2. Aceptaci&oacute;n expresa de manera personal</strong><br>Cuando los Datos Personales se obtengan personalmente del titular, Cin&eacute;polis&reg; pondr&aacute; a tu disposici&oacute;n el presente Aviso de Privacidad en el momento en que sean recabados tus Datos Personales y de una forma clara y fehaciente, por medio de los formatos que Cin&eacute;polis&reg; utiliza o llegare a utilizar para tal efecto. Adem&aacute;s, a trav&eacute;s de dichos formatos, Cin&eacute;polis&reg; recabar&aacute; la aceptaci&oacute;n o negaci&oacute;n del consentimiento del titular para someter dichos datos a las Finalidades del Tratamiento establecidas en el presente Aviso de Privacidad.</p>
<p><strong>5.1.3. Aceptaci&oacute;n expresa de manera telef&oacute;nica</strong><br>En el caso de los datos recabados conforme a lo establecido en el numeral 1.7 del presente Aviso de Privacidad, tal aceptaci&oacute;n ser&aacute; recabada de manera verbal por el personal que opere los servicios &nbsp;de Call Center y/o de operaci&oacute;n telef&oacute;nica que para tal efecto designe Cin&eacute;polis&reg;, para lo cual, dicha persona te invitar&aacute; a conocer el contenido del presente Aviso de Privacidad mismo que estar&aacute; disponible para tu consulta posterior en la p&aacute;gina www.cinepolis.com. En el caso de que no nos otorgues tu autorizaci&oacute;n previa y expresa para el tratamiento de tus datos personales conforme a lo establecido en el presente Aviso de Privacidad, te informamos que no podremos prestarte el servicio que solicites v&iacute;a telef&oacute;nica, ello debido a que tales datos son indispensables para poder realizar la transacci&oacute;n, comercializaci&oacute;n o prestaci&oacute;n del servicio.</p>
<p><strong>5.2. Aceptaci&oacute;n t&aacute;cita</strong><br>Con base en lo establecido en el art&iacute;culo 8 de la Ley y 14 de su Reglamento, el contenido de este Aviso de Privacidad, as&iacute; como cualquier modificaci&oacute;n o adici&oacute;n al mismo te ser&aacute;n dadas a conocer por cualquiera de los medios establecidos en los apartados 5.1.1. al 5.1.2. que anteceden, y en caso de que no manifiestes oposici&oacute;n al contenido y alcances de los mismos dentro de un periodo de 2 meses, contados a partir de la fecha en la que Cin&eacute;polis&reg; te informe sobre el presente Aviso de Privacidad o sus modificaciones, se entender&aacute; que otorgas tu consentimiento t&aacute;cito para que Cin&eacute;polis&reg; efect&uacute;e el tratamiento de tus Datos Personales con base en las Finalidades del Tratamiento establecidas en el Aviso de Privacidad.</p>
<p><strong>5.3. Aceptaci&oacute;n retroactiva</strong><br>Para todos nuestros clientes que en fechas anteriores a la notificaci&oacute;n o publicaci&oacute;n del presente Aviso de Privacidad nos hayan proporcionado sus Datos Personales, ya sea mediante el llenado de los formularios para la obtenci&oacute;n de membres&iacute;as, productos y/o servicios de Cin&eacute;polis&reg; y/o para la inscripci&oacute;n en la plataforma Cin&eacute;polis&reg; Jobs, o por cualquier otra forma o medio, les ser&aacute; dado a conocer el Aviso de Privacidad conforme a lo establecido en los apartados 5.1. y 5.2. que anteceden, con el fin de que nos otorguen o nieguen su consentimiento (expreso o t&aacute;cito) para Cin&eacute;polis&reg; pueda o no continuar llevando a cabo el Tratamiento de sus Datos Personales con base en las Finalidades del Tratamiento establecidas<br>en el Aviso de Privacidad.</p>
<p><strong>6. Limitaci&oacute;n del uso o divulgaci&oacute;n de tus Datos Personales<br></strong>6.1. Acciones para prevenir el uso o divulgaci&oacute;n no autorizada<br>Con el fin de garantizar la protecci&oacute;n de tus Datos Personales y limitar el uso o divulgaci&oacute;n no autorizada de los mismos, Cin&eacute;polis&reg; continuamente realiza y realizar&aacute; las siguientes acciones:<br>a) Confidencialidad de la informaci&oacute;n. Cin&eacute;polis&reg; guardar&aacute; confidencialidad respecto de tus Datos Personales recabados, misma que subsistir&aacute; aun despu&eacute;s de finalizar sus relaciones comerciales o de otra naturaleza con el cliente o titular de dichos Datos Personales.<br>b) Notificaci&oacute;n de confidencialidad. En caso de que, por alg&uacute;n motivo, Cin&eacute;polis&reg; se vea en la necesidad de proporcionar tus Datos Personales a terceros (en los t&eacute;rminos previstos en la Ley o en el presente Aviso de Privacidad), notificar&aacute; a dichos terceros la obligaci&oacute;n de cumplir con las disposiciones de la Ley y la confidencialidad de tus Datos Personales.<br>c) Administraci&oacute;n de bases de datos. Los Datos Personales son administrados y resguardados mediante el uso de bases de datos (&ldquo;Base de Datos&rdquo;), las cuales son administradas &uacute;nicamente por las &nbsp;personas designadas por Cin&eacute;polis&reg; para tal efecto, sin que se permita su uso, consulta, manejo o acceso a personas no autorizadas.<br>d) Sistemas de c&oacute;mputo e inform&aacute;ticos. Nuestras Bases de Datos est&aacute;n protegidas por firewalls y sistemas de c&oacute;mputo y/o inform&aacute;ticos enfocados a prevenir y evitar el que personas ajenas a Cin&eacute;polis&reg; o no autorizadas puedan acceder a tus Datos Personales.<br>e) Sistemas Antifraudes. Al momento de que nos proporciones tus datos bancarios en cualquiera de nuestros medios de venta o comercializaci&oacute;n de los productos y/o servicios de Cin&eacute;polis&reg;, se cuenta con diversas herramientas de protecci&oacute;n antifraudes, los cuales sirven para detectar operaciones extra&ntilde;as y proteger los datos bancarios de nuestros usuarios.</p>
<p><strong>6.2. Solicitudes para limitar el uso o divulgaci&oacute;n</strong><br>En caso que desees limitar el uso o divulgaci&oacute;n de tus Datos Personales, en relaci&oacute;n con una o varias de las Finalidades del Tratamiento de Datos Personales, como por ejemplo, correos publicitarios, promocionales, felicitaciones de cumplea&ntilde;os, ofertas de empleo, entrega de premios, entre otros, Cin&eacute;polis&reg; podr&aacute;s enviar la solicitud respectiva conforme al procedimiento establecido en el apartado 7 del presente Aviso de Privacidad, o mediante el acceso a los v&iacute;nculos que se cargan o llegaren a cargar en las p&aacute;ginas de internet de Cin&eacute;polis&reg; o en la informaci&oacute;n promocional que te&nbsp;hacemos llegar.</p>
<p><strong>7. Derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n</strong><br>De acuerdo con lo establecido en el art&iacute;culo 28 de la Ley, t&uacute; tienes derecho al acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n al Tratamiento de tus Datos Personales, para lo cual Cin&eacute;polis&reg; te ofrece el siguiente procedimiento:</p>
<p><strong>7.1. Departamento de Datos Personales</strong><br>Cin&eacute;polis&reg; ha designado un departamento a cargo de la custodia de los Datos Personales (en lo sucesivo &ldquo;Departamento de Datos Personales&rdquo;), el cual dar&aacute; tr&aacute;mite a tus solicitudes y fomentar&aacute; la protecci&oacute;n de los Datos Personales al interior de Cin&eacute;polis&reg;.</p>
<p>Para lo anterior, el Departamento de Datos Personales pone a tu disposici&oacute;n las siguientes formas de contacto y recepci&oacute;n de informaci&oacute;n y documentaci&oacute;n relacionada:</p>
<p>- Correo electr&oacute;nico: infodelcliente@cinepolis.com<br>- Direcci&oacute;n: Av. Cumbre de Naciones No. 1200, Zona Corporativos, Fraccionamiento Tres Mar&iacute;as<br>C.P. 58254, Morelia, Michoac&aacute;n.<br>Atenci&oacute;n: Departamento de Datos Personales.</p>
<p><strong>7.2. Solicitud de acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n</strong><br>En tu car&aacute;cter de titular de Datos Personales, podr&aacute;s presentar o enviar al Departamento de Datos Personales una solicitud para el acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n, respecto de tus Datos Personales.</p>
<p>De conformidad con el art&iacute;culo 29 de la Ley, dicha solicitud deber&aacute; contener, por lo menos:</p>
<p>- Nombre completo y domicilio del titular de los Datos Personales, u otro medio para comunicarle la respuesta a su solicitud.&nbsp;<br>- Documentos que acrediten la identidad o la representaci&oacute;n legal del titular de los Datos Personales.<br>- Descripci&oacute;n clara y precisa de los Datos Personales respecto de los que se busca ejercer alguno de los derechos antes mencionados.<br>- Cualquier otro elemento o documento que facilite la localizaci&oacute;n de los Datos Personales.<br>- Indicar de las modificaciones a realizarse y/o las limitaciones al uso de los Datos Personales, conforme a lo establecido en el apartado 6.2. del presente Aviso de Privacidad.<br>- Aportar la documentaci&oacute;n que sustente su petici&oacute;n.</p>
<p>Asimismo, en ciertos programas, productos, servicios o plataformas, Cin&eacute;polis&reg; podr&aacute; llegar a establecer mecanismos simplificados, adicionales o alternos para acreditar o autenticar la identidad del titular y/o su personalidad, tales como el uso de usuarios y/o contrase&ntilde;as espec&iacute;ficas, y/o como el uso de v&iacute;nculos o formatos especialmente dise&ntilde;ados para ello. Lo establecido en este p&aacute;rrafo, depender&aacute; del programa, producto, servicio o plataforma que se trate, para lo cual, te invitamos a consultar los t&eacute;rminos, condiciones, mec&aacute;nicas de uso o participaci&oacute;n y/o notas aclaratorias o informativas que se establecen al respecto, en nuestras p&aacute;ginas, sitios o micrositios de internet, informaci&oacute;n que se encontrar&aacute; ligada al programa, producto, servicio o plataforma que se trate.</p>
<p><strong>7.3. Resoluci&oacute;n y comunicaci&oacute;n</strong><br>Cin&eacute;polis&reg; comunicar&aacute; al titular de los Datos Personales la determinaci&oacute;n adoptada, en un plazo no mayor a 20 d&iacute;as h&aacute;biles contados desde la fecha en que se recibi&oacute; la solicitud. Este plazo podr&aacute; ser ampliado por Cin&eacute;polis&reg; en una sola ocasi&oacute;n por un periodo igual, siempre y cuando as&iacute; lo justifiquen las circunstancias del caso, lo anterior de conformidad con el art&iacute;culo 32 de la Ley.</p>
<p>Con base en lo anterior y de acuerdo con lo establecido en la Ley, Cin&eacute;polis&reg; informar&aacute; al titular de los Datos Personales el sentido y motivaci&oacute;n de la resoluci&oacute;n, por el mismo medio por el que se llev&oacute; a cabo la solicitud, y acompa&ntilde;ar&aacute; dicha resoluci&oacute;n de las pruebas pertinentes, en su caso.</p>
<p>Cuando la solicitud sea procedente, se har&aacute; efectiva por Cin&eacute;polis&reg; dentro de los 15 d&iacute;as h&aacute;biles siguientes a la comunicaci&oacute;n de la resoluci&oacute;n adoptada.</p>
<p>El titular podr&aacute; presentar ante el Instituto Nacional de Transparencia, Acceso a la Informaci&oacute;n y Protecci&oacute;n de Datos Personales (en lo sucesivo El INAI) una solicitud de protecci&oacute;n de datos por la respuesta recibida o falta de respuesta de Cin&eacute;polis&reg;. Dicha solicitud deber&aacute; presentarse por el titular dentro de los 15 d&iacute;as h&aacute;biles siguientes a la fecha en que se comunique la respuesta al titular por parte de Cin&eacute;polis&reg;, y se sujetar&aacute; a lo previsto en la Ley.</p>
<p>En caso de solicitudes de acceso a Datos Personales, ser&aacute; necesario que el solicitante o su representante legal acrediten previamente su identidad.</p>
<p>La obligaci&oacute;n de acceso a la informaci&oacute;n se dar&aacute; por cumplida cuando Cin&eacute;polis&reg; ponga a disposici&oacute;n del titular los Datos Personales o mediante la expedici&oacute;n de copias simples o documentos electr&oacute;nicos.</p>
<p>En el supuesto en que una persona solicite a Cin&eacute;polis&reg; el acceso a sus Datos Personales presumiendo que &eacute;ste es el responsable y resultara que no lo es, bastar&aacute; con que Cin&eacute;polis&reg; as&iacute; se lo indique al titular por cualquier medio, (de los establecidos en este apartado), para tener por desahogada la solicitud.&nbsp;</p>
<p>La contestaci&oacute;n a tu solicitud para acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n de los Datos Personales ser&aacute; gratuita. Deber&aacute;s cubrir &uacute;nicamente los gastos justificados de env&iacute;o o el costo de reproducci&oacute;n en copias u otros formatos, los cuales, en su momento, te har&aacute; saber Cin&eacute;polis&reg;.</p>
<p>En caso que la misma persona reitere la solicitud de acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n de los Datos Personales en un periodo menor a 12 meses contado a partir de la fecha de la &uacute;ltima solicitud, la contestaci&oacute;n a tu solicitud podr&aacute; tener un costo adicional que se&ntilde;ale Cin&eacute;polis&reg;, de acuerdo con lo establecido en art&iacute;culo 35 de la Ley.</p>
<p><strong>7.4. Negativa para acceder a Datos Personales</strong><br>Cin&eacute;polis&reg; de conformidad con el art&iacute;culo 26 de la Ley, podr&aacute; negar el acceso total o parcial a los Datos Personales o a la realizaci&oacute;n de la rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n al tratamiento de estos, en los siguientes supuestos:</p>
<p>- Cuando el solicitante no sea el titular o el representante legal no est&eacute; acreditado para ello.<br>- Cuando en la Base de Datos de Cin&eacute;polis&reg; no se encuentren los Datos Personales del solicitante.<br>- Cuando se lesionen los derechos de un tercero.<br>- Cuando exista impedimento legal o resoluci&oacute;n de una autoridad.<br>- Cuando la rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n haya sido previamente realizada, de manera que la solicitud carezca de materia.</p>
<p><strong>7.5. Consecuencias de la cancelaci&oacute;n</strong><br>La cancelaci&oacute;n de Datos Personales dar&aacute; lugar a un periodo de bloqueo tras el cual Cin&eacute;polis&reg; proceder&aacute; a la supresi&oacute;n de los datos correspondientes. Una vez cancelados los Datos Personales correspondientes, Cin&eacute;polis&reg; avisar&aacute; a su titular.</p>
<p>Hecho lo anterior, Cin&eacute;polis&reg; podr&aacute; conservar los Datos Personales exclusivamente para efectos de las responsabilidades derivadas del tratamiento a que se refiere el Aviso de Privacidad.</p>
<p>Cuando los Datos Personales se hubiesen transmitido a terceros o encargados antes de la rectificaci&oacute;n o cancelaci&oacute;n y sean tratados por dichos terceros, Cin&eacute;polis&reg; deber&aacute; hacer de su conocimiento la solicitud presentada por el titular, para que procedan a efectuar tales rectificaciones o cancelaciones.</p>
<p>Cin&eacute;polis&reg; no estar&aacute; obligado a cancelar tus Datos Personales cuando se trate de los supuestos establecidos en el art&iacute;culo 26 de la Ley, as&iacute; como tampoco cuando se trate de las finalidades a que se refiere el inciso h) del apartado 4 del presente Aviso de Privacidad, ello ya que las mismas dan origen o son necesarias para la existencia, mantenimiento o cumplimiento de una relaci&oacute;n u obligaci&oacute;n jur&iacute;dica.</p>
<p>Asimismo, cuando la informaci&oacute;n recabada en los Datos Personales deje de ser necesaria para el cumplimiento de las finalidades previstas en este Aviso de Privacidad y en las disposiciones jur&iacute;dicas aplicables, tus Datos Personales ser&aacute;n cancelados de las Bases de Datos de Cin&eacute;polis&reg;.</p>
<p><strong>8. Cambios al aviso de privacidad</strong><br>Cin&eacute;polis&reg; se reserva el derecho de efectuar, en cualquier momento, modificaciones o actualizaciones al presente Aviso de Privacidad, para la atenci&oacute;n de novedades legislativas o jurisprudenciales, pol&iacute;ticas internas, nuevos requerimientos para la prestaci&oacute;n u ofrecimiento de sus productos y servicios, o por pr&aacute;cticas comerciales.</p>
<p>Por lo anterior, en caso de que Cin&eacute;polis&reg; llegare a modificar el contenido del presente Aviso de Privacidad, lo har&aacute; de tu conocimiento mediante alguna de las formas y medios establecidos en el apartado 5 del presente Aviso.</p>
<p>El presente Aviso de Privacidad fue actualizado por &uacute;ltima ocasi&oacute;n el 01 de septiembre de 2021.</p>
<p><strong>9. Transferencia de Datos Personales</strong><br>Cin&eacute;polis podr&aacute; compartir los Datos Personales de los Titulares con sus proveedores, socios comerciales o terceros involucrados en alguna de las promociones, trivias, sorteos, en la comercializaci&oacute;n de los productos o servicios de Cin&eacute;polis&reg; y/o para poder llevar a cabo las Finalidades del Tratamiento establecidas en el presente Aviso de Privacidad, para lo cual ha celebrado o celebrar&aacute; diversos acuerdos comerciales tanto en territorio nacional como en el extranjero. Los receptores de los datos personales est&aacute;n obligados, por virtud del contrato correspondiente, a mantener la confidencialidad de los datos personales suministrados y a observar el presente Aviso, en el entendido de que los receptores bajo ning&uacute;n motivo podr&aacute;n compartir con terceros datos personales del Titular y asumir&aacute;n las mismas obligaciones que correspondan a Cin&eacute;polis&reg; como responsable del tratamiento.</p>
<p>Al aceptar este Aviso de Privacidad, otorgas tu autorizaci&oacute;n para que Cin&eacute;polis&reg; pueda transferir a administradores y/o responsables de las redes sociales (tales como Facebook&reg;, Twitter&reg;, YouTube&reg;, Linkedin&reg;, Instagram&reg; y/o las dem&aacute;s que de tiempo en tiempo est&eacute;n disponibles en el mercado), algunos de tus datos personales bajo los procesos y pol&iacute;ticas de estas plataformas, con el &uacute;nico objetivo de que coadyuven en enviarte informaci&oacute;n para lograr el objeto de las Finalidades del tratamiento de Datos Personales se&ntilde;aladas en el inciso a) y b), en tal caso tus datos tambi&eacute;n se regir&aacute;n por las pol&iacute;ticas y avisos de privacidad de dichas plataformas.</p>
<p>Su informaci&oacute;n personal puede remitirse en un pa&iacute;s distinto de donde se proporcion&oacute;, lo cual se llevar&aacute; a cabo de conformidad con las leyes de protecci&oacute;n de datos aplicables y de conformidad al presente aviso de privacidad, bajo ning&uacute;n motivo los terceros dentro o fuera del pa&iacute;s podr&aacute;n transferir y/o utilizar los datos proporcionados por Cin&eacute;polis&reg; con fines propios ajenos al presente aviso de privacidad. Tomamos medidas para proteger la informaci&oacute;n personal sin importar el pa&iacute;s donde se almacena o a donde se remite. Tenemos procedimientos y controles oportunos para procurar esta protecci&oacute;n.</p>
<p>Derivado de la transferencia a terceros a la que se hace menci&oacute;n en los p&aacute;rrafos anteriores, en cumplimiento al art&iacute;culo 36 de la Ley, usted manifiesta que, acepta la transferencia de sus datos a terceros.&nbsp;</p>
<p>No obstante, lo anterior, Cin&eacute;polis&reg; podr&aacute; comunicar los Datos Personales recolectados, a cualquier otra sociedad del mismo grupo empresarial al que pertenezca el Responsable y que operen con los mismos procesos y pol&iacute;ticas internas, ya sea que se encuentren en territorio nacional y/o en el extranjero, siendo su tratamiento con las mismas finalidades descritas en este Aviso, para lo cual no necesitar&aacute; el consentimiento del titular en virtud de la fracci&oacute;n III del art&iacute;culo 37 de la Ley.</p>
<p>Asimismo, Cin&eacute;polis&reg; no requiere el consentimiento del Titular para realizar transferencias de datos personales nacionales y/o internacionales en los casos previstos en el Art&iacute;culo 37 de la Ley o en cualquier otro caso de excepci&oacute;n previsto por la misma u otra legislaci&oacute;n aplicable, lo anterior, siempre y cuando se act&uacute;e conforme a lo establecido en el presente Aviso de Privacidad.&nbsp;</p>
<h2>Consideraciones Finales</h2>
<p>Al momento de completar el registro para recibir alguno de los productos de Cin&eacute;polis&reg; (revistas impresas o electr&oacute;nicas, boletines electr&oacute;nicos, as&iacute; como cualquiera que requiera una suscripci&oacute;n para poder obtenerlos); cuando realices transacciones para la compra de boletos y/o alimentos en cualquiera de nuestras plataformas digitales (mediante equipos m&oacute;viles y/o cualquier otra plataforma, sitios y/o micrositios web que de tiempo en tiempo utilice Cin&eacute;polis&reg;); cuando realices transacciones y/o operaciones relacionadas y/o al interior de la plataforma de CineCash y/o de cualquier otra que de tiempo en tiempo este vigente y cuando realices tu registro de Cin&eacute;polis ID, Club Cin&eacute;polis, Membres&iacute;a Cin&eacute;polis, de forma personal o digital; manifiestas, voluntariamente y de forma expresa, que has le&iacute;do y comprendido el alcance sobre el tratamiento que Exhibidora Mexicana Cin&eacute;polis, S.A. de C.V., da a los datos personales, por lo que no tienes observaciones ni inquietudes respecto del mismo, por lo cual, a trav&eacute;s del presente aviso, manifiestas de forma libre, consciente, expresa, informada y espont&aacute;nea que autorizas a Exhibidora Mexicana Cin&eacute;polis, S.A. de C.V. para dar tratamiento de tus datos personales acorde con lo establecido en este formato.</p>
<p>&nbsp;</p>
            ',
			'slug'          => 'aviso-de-privacidad',
			'active'        => true,
			'icon'			=> '/storage/dummy_assets/shield.png',
		]);

		Page::create([
			'id'            => 2,
			'title'         => 'Términos y Condiciones',
			'description'   => 'Términos y condiciones de los concursos.',
			'content'       => '
            <p>Promoci&oacute;n v&aacute;lida para unas palomitas JUMBO sabor TAKIS BLUE HEAT a $50 MXN.</p>
<p>&bull; Sujeto a disponibilidad en conjunto<br>&bull; Cup&oacute;n canieable en dulcer&iacute;a<br>&bull; Cup&oacute;n v&aacute;lido de lunes a domingo o Valido al 30 de Noviembre 2023<br>&bull; V&aacute;lido &uacute;nicamente en dulcer&iacute;as de Cin&eacute;polis Tradicional<br>&bull; No v&aacute;lido con otras promociones ni en paquetes armados o No v&aacute;lido para otros productos de dulcer&iacute;a<br>&bull; No v&aacute;lido en dulcer&iacute;a de Cin&eacute;polis Vip, Cinema Park y Xtreme o No se podr&aacute; cambiar por dinero en efectivo<br>&bull; Una operaci&oacute;n por cliente.</p>
            <p>El uso de este sitio web cinepolis.com o de cualquiera de sus componentes (en lo sucesivo &ldquo;el Sitio&rdquo;), implica la aceptaci&oacute;n expresa de los presentes &ldquo;T&eacute;rminos y Condiciones&rdquo;, de su Aviso de Privacidad integral y de su Aviso de Privacidad simplificado, as&iacute; como de los otros T&eacute;rminos y Condiciones especiales de los servicios y/o productos comercializados en este Sitio.</p>
<p>El contenido del Sitio, as&iacute; como sus actualizaciones, son propiedad exclusiva de Exhibidora Mexicana Cin&eacute;polis, S.A. de C.V., y/o de sus empresas afiliadas y/o subsidiarias (en lo sucesivo &ldquo;Cin&eacute;polis&rdquo;) y se encuentran protegidos por las leyes de los Estados Unidos Mexicanos, as&iacute; como por el Derecho Internacional.</p>
<p>&nbsp;El Sitio, debe ser usado como un recurso de publicidad e informaci&oacute;n de los bienes y servicios que ofrece Cin&eacute;polis.</p>
<p>Cualquier uso, como los publicitarios, republicaci&oacute;n, distribuci&oacute;n, comunicaci&oacute;n p&uacute;blica, transformaci&oacute;n, exhibici&oacute;n, ejecuci&oacute;n o comercializaci&oacute;n del contenido de este sitio, incluyendo las marcas o avisos comerciales, en alguna red de c&oacute;mputo o p&aacute;gina de Internet se encuentra estrictamente prohibido sin el previo consentimiento por escrito de Cin&eacute;polis.</p>
<p>&nbsp;El usuario se obliga a no da&ntilde;ar, inutilizar o deteriorar los sistemas inform&aacute;ticos de este Sitio, ni los contenidos incorporados y/o almacenados en &eacute;ste; no modificar de ninguna manera los sistemas y/o componentes del Sitio; no utilizar versiones de sistemas modificados con el fin de obtener acceso no autorizado a cualquier sistema de informaci&oacute;n, contenido y/o servicios del Sitio; no interferir ni interrumpir el acceso, funcionalidad y utilizaci&oacute;n del Sitio, servidores o redes conectados al mismo, o incumplir los requisitos, procedimientos y regulaciones de dicho Sitio.</p>
<p>Las marcas Cin&eacute;polis&reg;, Cin&eacute;polis VIP&reg;, Cin&eacute;polis Digital&reg;, Macro XE&reg;, 4Dx&reg;, IMAX&reg;, Cin&eacute;polis Junior&reg;, Cin&eacute;polis Pluus&reg;, Xtreme&reg;, Mi Cine Cin&eacute;polis&reg; Diversi&oacute;n a tu Alcance&reg;, CinemaStar&reg;, Cineticket&reg;, Cin&eacute;polis VR&reg;, Club Cin&eacute;polis&reg;, +Que cine Cin&eacute;polis&reg;, Cinecash, as&iacute; como todas y cada una de las marcas que forman parte de los productos y servicios englobados en el concepto comercialmente conocido como Cin&eacute;polis&reg; y sus diferentes dise&ntilde;os se encuentran debidamente registrados y/o licenciados a favor de Cin&eacute;polis, por lo que su uso total o parcial est&aacute; estrictamente prohibido y sujeto a las sanciones y penas establecidas en las leyes aplicables.</p>
<p>Todo el dise&ntilde;o de este sitio, contenidos, incluyendo sus dise&ntilde;os, gr&aacute;ficos, fotograf&iacute;as, textos, informaci&oacute;n y programas de c&oacute;mputo asociados, y/o cualquier otro derecho protegido por la legislaci&oacute;n aplicable en materia de Propiedad Intelectual son derechos reservados y exclusivos de Cin&eacute;polis.</p>
<p>&nbsp;Cin&eacute;polis se&ntilde;ala como domicilio el ubicado en Av. Cumbre de Naciones 1200, Fraccionamiento Tres Mar&iacute;as, en la ciudad de Morelia, Michoac&aacute;n, M&eacute;xico.</p>
<p>La informaci&oacute;n contenida en este Sitio es s&oacute;lo enunciativa, por lo que de ninguna manera constituye una oferta vinculante que obligue al usuario y a Cin&eacute;polis, a celebrar contrato alguno en relaci&oacute;n con tales operaciones.</p>
<p>Cin&eacute;polis, se reservan el derecho de modificar la informaci&oacute;n aqu&iacute; contenida cuando lo estime conveniente y sin previo aviso, pudiendo incluso limitar o no permitir el acceso a dicha informaci&oacute;n, por lo que te pedimos revises constantemente los presentes T&eacute;rminos y Condiciones. Cin&eacute;polis, no se responsabilizan por da&ntilde;os o perjuicios derivados del acceso, uso o mala utilizaci&oacute;n de los contenidos de este sitio; de las posibles discrepancias que puedan surgir entre la versi&oacute;n de sus documentos impresos y la versi&oacute;n electr&oacute;nica de los mismos publicados en este sitio; no se asume responsabilidad alguna con los contenidos y servicios comerciales o de otra &iacute;ndole, p&aacute;ginas webs que se puedan enlazar electr&oacute;nicamente (link) directa o indirectamente a trav&eacute;s del portal de www.cinepolis.com y/o www.cineticket.com.mx y/o cualquier otro que administre Cin&eacute;polis, no se asume responsabilidad alguna que derive del intercambio de informaci&oacute;n electr&oacute;nica entre usuarios de la red Internet, as&iacute; tambi&eacute;n no se adquiere ninguna responsabilidad por causa de problemas t&eacute;cnicos que se pudieran producir en equipos inform&aacute;ticos que se utilicen durante la conexi&oacute;n a la red Internet, ya sea a trav&eacute;s del presente portal o de otras p&aacute;ginas webs. Las operaciones que pueden realizarse a trav&eacute;s de este Sitio se regir&aacute;n por los presentes T&eacute;rminos y Condiciones y/o por los del servicio o producto aplicable seg&uacute;n corresponda, los cuales est&aacute;n acordes a la legislaci&oacute;n mercantil, civil, de protecci&oacute;n al consumidor y dem&aacute;s aplicables, vigentes en la Rep&uacute;blica Mexicana.</p>
<p>Cualquier controversia que se derive de la aplicaci&oacute;n de las mismas se ventilar&aacute; ante los tribunales de la ciudad de M&eacute;xico, renunciando las partes expresamente a cualquier otra jurisdicci&oacute;n que les pudiera corresponder por raz&oacute;n de su domicilio presente o futuro o por cualquier otra causa. Todos los derechos reservados, sobre el Sitio.</p>
<p>Aviso de Privacidad. En cumplimiento de la Ley Federal de Protecci&oacute;n de Datos Personales y de su Reglamento, le informamos que para las operaciones y actividades que se realicen en este Sitio se sujetar&aacute; al contenido del Aviso de Privacidad de Cin&eacute;polis&reg; el cual, se encuentra publicado para tu consulta en https://static.cinepolis.com/resources/mx/documents/aviso-de-privacidadcinepolis.pdf</p>
            ',
			'slug'          => 'terminos-y-condiciones',
			'active'        => true,
			'icon'			=> '/storage/dummy_assets/policy.png',
		]);

		Page::create([
			'id'            => 3,
			'title'         => 'Dinámica de la Promoción',
			'description'   => 'Cómo se realiza la dinámica Takis Cinépolis.',
			'content'       => '
            <p>Participa y g&aacute;nate un cup&oacute;n de descuento para disfrutar de tus palomitas Blue Heat Takis jumbo a solo $50 pesos.</p>
<ol>
<li>Ingresa en www.cineplay.mx/takis</li>
<li>Reg&iacute;strate con tus datos correctamente (nombre, correo electr&oacute;nico y contrase&ntilde;a)</li>
<li>Contesta correctamente la trivia takillera</li>
<li>Si fuiste ganador, presenta tu cup&oacute;n en la dulcer&iacute;a de Cin&eacute;polis con el c&oacute;digo de descuento.</li>
</ol>
<p>V&aacute;lido durante el mes de noviembre del 2023.</p>
<p><a class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" href="https://cineplay.mx/">Jugar</a></p>
            ',
			'slug'          => 'dinamica-de-la-promocion',
			'active'        => true,
			'icon'			=> '/storage/dummy_assets/speaker.png'
		]);

		Page::create([
			'id'            => 4,
			'title'         => 'Preguntas Frequentes',
			'description'   => 'Preguntas a respuestas frecuentes.',
			'content'       => '
<div id="accordion-collapse" data-accordion="collapse">
<h2 id="accordion-collapse-heading-1">
  <button type="button" class="flex items-center justify-between w-full p-5 font-medium text-left text-gray-500 border border-b-0 border-gray-200 rounded-t-xl focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 dark:border-gray-700 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800" data-accordion-target="#accordion-collapse-body-1" aria-expanded="true" aria-controls="accordion-collapse-body-1">
    <span>What is Flowbite?</span>
    <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
    </svg>
  </button>
</h2>
<div id="accordion-collapse-body-1" class="hidden" aria-labelledby="accordion-collapse-heading-1">
  <div class="p-5 border border-b-0 border-gray-200 dark:border-gray-700 dark:bg-gray-900">
    <p class="mb-2 text-gray-500 dark:text-gray-400">Flowbite is an open-source library of interactive components built on top of Tailwind CSS including buttons, dropdowns, modals, navbars, and more.</p>
    <p class="text-gray-500 dark:text-gray-400">Check out this guide to learn how to <a href="/docs/getting-started/introduction/" class="text-blue-600 dark:text-blue-500 hover:underline">get started</a> and start developing websites even faster with components on top of Tailwind CSS.</p>
  </div>
</div>
<h2 id="accordion-collapse-heading-2">
  <button type="button" class="flex items-center justify-between w-full p-5 font-medium text-left text-gray-500 border border-b-0 border-gray-200 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 dark:border-gray-700 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800" data-accordion-target="#accordion-collapse-body-2" aria-expanded="false" aria-controls="accordion-collapse-body-2">
    <span>Is there a Figma file available?</span>
    <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
    </svg>
  </button>
</h2>
<div id="accordion-collapse-body-2" class="hidden" aria-labelledby="accordion-collapse-heading-2">
  <div class="p-5 border border-b-0 border-gray-200 dark:border-gray-700">
    <p class="mb-2 text-gray-500 dark:text-gray-400">Flowbite is first conceptualized and designed using the Figma software so everything you see in the library has a design equivalent in our Figma file.</p>
    <p class="text-gray-500 dark:text-gray-400">Check out the <a href="https://flowbite.com/figma/" class="text-blue-600 dark:text-blue-500 hover:underline">Figma design system</a> based on the utility classes from Tailwind CSS and components from Flowbite.</p>
  </div>
</div>
<h2 id="accordion-collapse-heading-3">
  <button type="button" class="flex items-center justify-between w-full p-5 font-medium text-left text-gray-500 border border-gray-200 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 dark:border-gray-700 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800" data-accordion-target="#accordion-collapse-body-3" aria-expanded="false" aria-controls="accordion-collapse-body-3">
    <span>What are the differences between Flowbite and Tailwind UI?</span>
    <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
    </svg>
  </button>
</h2>
<div id="accordion-collapse-body-3" class="hidden" aria-labelledby="accordion-collapse-heading-3">
  <div class="p-5 border border-t-0 border-gray-200 dark:border-gray-700">
    <p class="mb-2 text-gray-500 dark:text-gray-400">The main difference is that the core components from Flowbite are open source under the MIT license, whereas Tailwind UI is a paid product. Another difference is that Flowbite relies on smaller and standalone components, whereas Tailwind UI offers sections of pages.</p>
    <p class="mb-2 text-gray-500 dark:text-gray-400">However, we actually recommend using both Flowbite, Flowbite Pro, and even Tailwind UI as there is no technical reason stopping you from using the best of two worlds.</p>
    <p class="mb-2 text-gray-500 dark:text-gray-400">Learn more about these technologies:</p>
    <ul class="pl-5 text-gray-500 list-disc dark:text-gray-400">
      <li><a href="https://flowbite.com/pro/" class="text-blue-600 dark:text-blue-500 hover:underline">Flowbite Pro</a></li>
      <li><a href="https://tailwindui.com/" rel="nofollow" class="text-blue-600 dark:text-blue-500 hover:underline">Tailwind UI</a></li>
    </ul>
  </div>
</div>
</div>
            ',
			'slug'          => 'preguntas-frecuentes',
			'active'        => false,
			'icon'			=> '/storage/dummy_assets/faq.png',
		]);

		DB::statement('SET FOREIGN_KEY_CHECKS=1;');
	}
}
